# Configuración de Netlify para Estudio Daniel Merquiz
[build]
  # Directorio de publicación (donde están los archivos web)
  publish = "."
  
  # Comando de build (no necesario para sitio estático)
  command = "echo 'Static site ready'"

[build.environment]
  # Variables de entorno
  NODE_VERSION = "18"

# Configuración de redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de redirects para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuración de headers para mejorar seguridad y rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    # Seguridad
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # CORS para Firebase
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, Authorization"

# Headers específicos para HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
